# Generated by Django 5.2.5 on 2025-08-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allow_dms_from',
            field=models.CharField(choices=[('everyone', 'Everyone can dm me'), ('friends', 'Only friends can dm me'), ('none', 'No one can dm me')], default='everyone', max_length=20),
        ),
    ]
