# Generated by Django 5.2.5 on 2025-08-23 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingo_channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pingo_channels.channel'),
            preserve_default=False,
        ),
    ]
